name: MewChat CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build and Deploy on Debian
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Go Server
      run: |
        cd server
        go build -v -o mewchat-server ./cmd/app/main.go

    - name: Run Application
      env:
        RUNNER_TRACKING_ID: ""
      run: |
        cd server
        pkill mewchat-server || true
        nohup ./mewchat-server > server.log 2>&1 &