name: MewChat CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build and Deploy on Debian
    # Указываем GitHub использовать наш домашний раннер вместо облачного ubuntu-latest
    runs-on: self-hosted

    steps:
    # Шаг 1: Скачиваем свежий код из гитхаба в рабочую папку раннера на ноутбуке
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Собираем бинарник прямо на ноутбуке
    - name: Build Go Server
      run: |
        cd server
        go build -v -o mewchat-server ./cmd/app/main.go

    # Шаг 3: Запуск приложения в фоне (пока в простом режиме screen или nohup)
    - name: Run Application
      run: |
        cd server
        # Убиваем старый процесс сервера, если он был запущен, чтобы освободить порт
        pkill mewchat-server || true
        # Запускаем новый бинарник в фоне, чтобы пайплайн не завис в ожидании
        nohup ./mewchat-server > server.log 2>&1 &